# Generated by Django 2.2.4 on 2019-08-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userask',
            old_name='moblie',
            new_name='mobile',
        ),
    ]
