# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-08-15 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='datail',
            new_name='detail',
        ),
    ]
