# Generated by Django 2.2.4 on 2019-08-17 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20190817_1954'),
        ('courses', '0004_courseresource_course_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseresource',
            name='course_org',
        ),
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='课程机构'),
        ),
    ]
