# Generated by Django 2.2.4 on 2019-08-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lesson_learn_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='learn_times',
        ),
        migrations.AddField(
            model_name='video',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='学习时长(分钟数)'),
        ),
    ]
