# Generated by Django 2.2.4 on 2019-08-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20190819_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_path',
            field=models.FileField(default='', upload_to='course/video/%Y/%m', verbose_name='视频文件'),
        ),
    ]
