# Generated by Django 2.2.4 on 2019-08-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_video_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否轮播'),
        ),
    ]
